joshu/joshu/urls.py
#from django.conf.urls import url
from django.urls import include, re_path as url
from django.contrib import admin
from django.urls import path, include
from django.views.decorators.csrf import csrf_exempt

from rest_framework import permissions
from drf_yasg.views import get_schema_view
from drf_yasg import openapi
from telegram_bot.views import TelegramBotView
from main.views import index

schema_view = get_schema_view(
    openapi.Info(
        title="Joshu API",
        default_version='v1',
        description="Joshu API v1",
        # terms_of_service="https://www.google.com/policies/terms/",
        # contact=openapi.Contact(email="contact@snippets.local"),
        license=openapi.License(name="BSD License"),
    ),
    public=True,
    permission_classes=(permissions.AllowAny,),
)

urlpatterns = [
    url(r'^$', index, name='index'),
    path('admin/', admin.site.urls),

    # API
    path('api/v1/', include('joshuAPI.urls', namespace='joshu_api')),

    # Swagger
    url(r'^swagger(?P<format>\.json|\.yaml)$', schema_view.without_ui(cache_timeout=0), name='schema-json'),
    url(r'^swagger/$', schema_view.with_ui('swagger', cache_timeout=0), name='schema-swagger-ui'),
    url(r'^redoc/$', schema_view.with_ui('redoc', cache_timeout=0), name='schema-redoc'),

    # Telegram_bot
    path('webhooks/telegram_bot/', csrf_exempt(TelegramBotView.as_view())),

    # MainApp
    path('main/', include('main.urls', namespace='main_app')),

    # CeleryProgress
    path('celery-progress/', include('celery_progress.urls')),

]

joshu/main/urls.py
from django.urls import path
from main.views import message_detail, get_task_info, RcLoginView, RcLogoutView, all_message, AdmBotMessageUpdate, \
    AdmBotMessageCreate, AdmBotMessageDelete

app_name = 'main_app'

urlpatterns = [
    # Message
    path('messages_all/', all_message, name='messages_all'),
    path('message_detail/<int:pk>/', message_detail, name='message_detail'),
    path('message_update/<int:pk>/', AdmBotMessageUpdate.as_view(), name='message_update'),
    path('message_create/', AdmBotMessageCreate.as_view(), name="message_create"),
    path('message_delete/<int:pk>/', AdmBotMessageDelete.as_view(), name="message_delete"),

    # Celery-result
    path('get-task-info/', get_task_info),

    # Profile
    path('login/', RcLoginView.as_view(), name='login'),
    path('logout/', RcLogoutView.as_view(), name='logout'),
]

joshu/main/models.py
from django.db import models
from django.contrib import admin


class AdmBotMessage(models.Model):
    name = models.CharField(max_length=256, verbose_name="Короткое название")
    description = models.TextField(verbose_name='Содержание сообщения', blank=True)

    class Meta:
        verbose_name_plural = "Сообщения"
        verbose_name = "Сообщение"
        ordering = ['name']

    def __str__(self):
        return f"{self.name}"


@admin.register(AdmBotMessage)
class AdminMessage(admin.ModelAdmin):
    list_display = ('name', )


class DataSendMessage(models.Model):
    message = models.ForeignKey(AdmBotMessage, on_delete=models.CASCADE, verbose_name='Сообщение')
    date_time = models.DateTimeField(auto_now_add=True, verbose_name='Дата рассылки')

    class Meta:
        verbose_name_plural = "Даты рассылки"
        verbose_name = "Дата рассылки"
        ordering = ['date_time']

    def __str__(self):
        return f"{self.date_time}"


@admin.register(DataSendMessage)
class AdminDataSendMessage(admin.ModelAdmin):
    list_display = ('message', 'date_time')

joshu/main/forms.py
from django import forms

from main.models import AdmBotMessage


class SendForm(forms.Form):
    message = forms.ModelChoiceField(queryset=AdmBotMessage.objects.all(), label='', disabled=True)

    def __init__(self, pk, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['message'].initial = AdmBotMessage.objects.get(pk=pk)

    class Meta:
        model = AdmBotMessage
        fields = ('message',)
        widgets = {'message': forms.HiddenInput, }

joshu/main/views.py
from django.contrib.auth.decorators import login_required, permission_required
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic
from django.contrib import messages
from django.views.generic import UpdateView, CreateView, DeleteView

from joshuAPI.models import JoshuUser
from main.forms import SendForm
from main.models import AdmBotMessage, DataSendMessage
from celery.result import AsyncResult
from main.tasks import send_messages
from django.http import HttpResponse
import json
from django.contrib.auth.views import LoginView, LogoutView
from django.shortcuts import resolve_url
from joshu import settings


def index(request):
    context = {
        'title': 'Главная страница'
    }
    return render(request, 'index.html', context)


# ----------------
class RcLoginView(LoginView):
    template_name = 'profile/login.html'

    def get_success_url(self):
        return resolve_url(settings.LOGIN_REDIRECT_URL)

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Вход пользователя'
        return context


class RcLogoutView(LoginRequiredMixin, LogoutView):
    template_name = 'profile/logout.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Выход пользователя'
        return context


# ----------------
@login_required
def all_message(request):
    all_messages = AdmBotMessage.objects.all()
    data_query = []  # дамп данных который пойдет на фронт

    for item_message in all_messages:
        all_send = DataSendMessage.objects.filter(message=item_message)
        data_item_query = {
            'name': item_message.name,
            'pk_messages': item_message.pk,
            'all_send': all_send
        }
        data_query.append(data_item_query)

    context = {
        'title': 'Все сообщения',
        'data_query': data_query
    }
    return render(request, 'messages_all.html', context)


@login_required
def message_detail(request, pk):
    pattern = '[\d]+'
    user_co = JoshuUser.objects.filter(chat_id__iregex=pattern).count()

    if request.method == 'POST':
        form = SendForm(pk, request.POST)
        task = send_messages.delay(pk)

        messages.add_message(request, messages.SUCCESS, 'Отсылаю пользователям...')

        context = {
            'form': form,
            'title': 'Сообщение детально',
            'current_message': AdmBotMessage.objects.get(pk=pk),
            'user_count': user_co,
            'task_id': task.task_id
        }
        return render(request, 'message_detail.html', context)

    else:
        form = SendForm(pk)

    context = {
        'form': form,
        'title': 'Сообщение детально',
        'current_message': AdmBotMessage.objects.get(pk=pk),
        'user_count': user_co
    }
    return render(request, 'message_detail.html', context)


class AdmBotMessageUpdate(LoginRequiredMixin, UpdateView):
    fields = '__all__'
    template_name = 'create_update_admbotmessage.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['set_title'] = 'Редактирование cообщения'
        context['title'] = 'Редактирование cообщения'
        return context

    def get_queryset(self):
        return AdmBotMessage.objects.all()

    def get_success_url(self):
        return reverse_lazy('main_app:message_detail', kwargs={'pk': self.kwargs.get('pk')})


class AdmBotMessageCreate(LoginRequiredMixin, CreateView):
    model = AdmBotMessage
    template_name = 'create_update_admbotmessage.html'
    fields = '__all__'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['set_title'] = 'Создание cообщения'
        context['title'] = 'Создание cообщения'
        return context

    def get_success_url(self):
        # return reverse_lazy('blog_app:blog_detail', kwargs={'pk': self.kwargs.get('pk')})
        return reverse_lazy('main_app:messages_all')


class AdmBotMessageDelete(LoginRequiredMixin, DeleteView):
    model = AdmBotMessage
    success_url = reverse_lazy('main_app:messages_all')
    template_name = 'admbotmessage_confirm_delete.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['title'] = 'Удаление cообщения'
        context['set_title'] = 'Удаление cообщения'
        return context


# --------------------------------------------------------------
# функция для работы прогресс бара
def get_task_info(request):
    task_id = request.GET.get('task_id', None)
    if task_id is not None:
        task = AsyncResult(task_id)
        data = {
            'state': task.state,
            'result': task.result,
        }
        return HttpResponse(json.dumps(data), content_type='application/json')
    else:
        return HttpResponse('No job id given.')

joshu/main/templates/admbotmessage_confirm_delete.html
{% extends "base_generic.html" %}

{% load static %}

{% block breadcrumbs %}
    <a href="/">Начало /</a>
	<a href="/main/messages_all/">Все сообщения /</a>
    {% if admbotmessage %}
	    <a href="{% url 'main_app:message_detail' admbotmessage.pk  %}">{{ admbotmessage.name }} /</a>
    {% endif %}
    {{ set_title }}
{% endblock %}

{% block content %}
<style>
    .block-content{width: 1200px;}
</style>

    <div>
        <h1 style="text-align: center">{{ set_title }}
            {% if admbotmessage %}
                "{{ admbotmessage.name }}"
            {% endif %}
        </h1>
        {% if user.is_authenticated and user.telegram_ch_admin %}
        <div class="block-content">
        <p>Вы уверены, что хотите удалить сообщение:  <b style="color:red">{{ admbotmessage.name }}</b>?</p>
        {#-------------------------------------#}
            <form action="" method="POST">
			  {% csrf_token %}
			  <input type="submit" action="" value="Да, удалить" />
			</form>
        {#-------------------------------------#}
        </div>
        {% endif %}
    </div>

{% endblock %}

joshu/main/templates/base_generic.html
{% load static %}
{% load bootstrap4 %}
<!DOCTYPE html>
<html lang="en">
<head>
    {% if title %}
    <title>{{ title }}</title>
    {% else %}
    <title>Joshu App</title>
    {% endif %}
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    {% if description %}
    <meta name="description" content="{{ description }}"/>
    {% else %}
    <meta name="description" content="Welcome to Joshu App"/>
    {% endif %}

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css"
        integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">

    {% load static %}
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">
    <link rel="icon" href="{% static 'favicon.ico' %}"/>

    <!--script type="text/javascript" src="https://code.jquery.com/jquery-latest.min.js"></script-->

</head>

<body>

<div class="middle-header">
  <div class="sub-middlehead">
      {% include 'includes/navblock.html' %} <!-- Меню -->
  </div>

</div>
<div class="breadcrumbs">
    {% block breadcrumbs %}

    {% endblock %}
</div>
<div class="container base_content">

        <section>
          {% block content %}

          {% endblock %}

          {% block content2 %}
          {% endblock %}
        </section>

</div>

<script src="{% static 'js/jquery-3.4.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

{% block script %}

{% endblock %}



  <!--script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js"
  integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script-->
  <!--script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js"
  integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script-->

</body>
</html>

joshu/main/templates/create_update_admbotmessage.html
{% extends "base_generic.html" %}

{% load static %}

{% block breadcrumbs %}
    <a href="/">Начало /</a>
	<a href="/main/messages_all/">Все сообщения /</a>
    {% if admbotmessage %}
	    <a href="{% url 'main_app:message_detail' admbotmessage.pk  %}">{{ admbotmessage.name }} /</a>
    {% endif %}
    {{ set_title }}
{% endblock %}

{% block content %}
<style>
    .block-content{width: 1200px;}
</style>

    <div>
        <h1 style="text-align: center">{{ set_title }}
            {% if admbotmessage %}
                "{{ admbotmessage.name }}"
            {% endif %}
        </h1>
        {% if user.is_authenticated and user.telegram_ch_admin %}
        <div class="block-content">
        {#-------------------------------------#}
        <form method="post">
            {% csrf_token %}
            <table>
                {{ form.as_p }}
            </table>

            <input type="submit" value="Сохранить">
        </form>
        {#-------------------------------------#}
        </div>
        {% endif %}
    </div>

{% endblock %}

joshu/main/templates/index.html
{% extends "base_generic.html" %}

{% load static %}

{% block breadcrumbs %}
    Начало /
{% endblock %}

{% block content %}
    <div>
        <h1 style="text-align: center">Welcome to Joshu</h1>
        <div class="block-content">
            <p>API Documentation:</p>
            <ul>
                <li><a href="/swagger/">Swagger</a> </li>
                <li><a href="/redoc/">Redoc</a> </li>
            </ul>
        </div>
        {% if user.is_authenticated and user.telegram_ch_admin %}
            <div class="block-content">
                <p>Сообщения Чат-бота Telegram</p>
                <ul>
                    <li><a href="{% url 'main_app:messages_all' %}">Перейти</a> </li>
                </ul>
            </div>
        {% endif %}
    </div>

{% endblock %}

joshu/main/templates/message_detail.html
{% extends "base_generic.html" %}

{% load static %}

{% block breadcrumbs %}
	<a href="/">Начало /</a>
	<a href="/main/messages_all/">Все сообщения /</a>
	{{ current_message.name }}
{% endblock %}

{% block script %}
	{% if task_id %}
   	    <script src="{% static '/js/progress-bar.js' %}"></script>
    {% endif %}
{% endblock %}

{% block content %}
<style>
    .block-content{width: 1200px;}
</style>


<div>
    <h1 style="text-align: center">Cообщение Чат-бота детально</h1>
    {% if user.is_authenticated and user.telegram_ch_admin %}
    <div class="block-content">
        <p><b>Короткое название:</b> {{ current_message.name }}</p>
        <p><b>Содержание сообщения:</b> {{ current_message.description }}</p>
		<br>
		<p><a href="{% url 'main_app:message_update' current_message.pk %}">Редактировать сообщение</a></p>
		<p><a href="{% url 'main_app:message_delete' current_message.pk %}">Удалить сообщение</a> </p>
    </div>

    <div class="block-content">
        <b>Пользователей в чат бот:</b> {{ user_count }}
		<br>
        {#-------------------------------------#}

              <form id="generate-objects" method="post">
					{% csrf_token %}
					<table>
						{{ form.as_p }}
					</table>
					<input type="submit" value="Отослать сообщение">
				</form>

            {#-------------------------------------#}
    </div>
    {% endif %}
</div>

<div>
    {% if messages %}
	<ul class="messages">
		{% for message in messages %}
			<li class="{{ message.tags }}">
				{{ message|safe }}
			</li>
		{% endfor %}
	</ul>
	{% else %}
		<p></p>
	{% endif %}
</div>


<div class="progress-block" id="ProgressBlock"
	 progress-url="/celery-progress/{{ task_id }}/">
</div>

{% if task_id %}
<progress id="progress-bar" value="0" max="100" style="display:block; margin-bottom: 1em;width: 100%">

</progress>

<div id="messages_task">
    <p>-</p>
</div>
{% endif %}
{% endblock %}

joshu/main/templates/messages_all.html
{% extends "base_generic.html" %}

{% load static %}

{% block breadcrumbs %}
    <a href="/">Начало /</a>
    Все сообщения
{% endblock %}

{% block content %}
<style>
    .block-content{width: 1200px;}
</style>

    <div>
        <h1 style="text-align: center">Все сообщения Чат-бота</h1>
        {% if user.is_authenticated and user.telegram_ch_admin %}
        <div style="width: 1200px;">
            <table style="width: 100%; valign: top">
                <tbody>
                <tr style="border-bottom: 2px solid #c2c2c2;">
                    <th class="head-row">Название</th>
                    <th class="head-row">Дата отправлений</th>
                </tr>

                    {% if data_query %}
                        {% for item in data_query %}
                            <tr class="mes-row">
                                <td><a href="{% url 'main_app:message_detail' item.pk_messages %}">{{ item.name }}</a></td>
                                <td>
                                    {% if item.all_send %}
                                        {% for i in item.all_send %}
                                            {{ i.date_time|date:"D d M Y" }} {{ i.date_time|time:"H:i" }},<br>
                                        {% endfor %}
                                    {% else %}
                                        -
                                    {% endif %}
                                </td>
                            </tr>
                        {% endfor %}
                    {% else %}
                        <tr>
                            <td>Пусто</td>
                        </tr>
                    {% endif %}
                </tbody>
            </table>
        </div>
        <br>
        <p><a href="{% url 'main_app:message_create' %}">Добавить сообщение</a></p>
        {% endif %}
    </div>

{% endblock %}